name: CI

on:
  push:
    branches: [ main, master, develop, feature/** ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          # Evita falhas por checagem de conectividade em ambientes sem Neo4j
          NEO4J_VERIFY_CONNECTIVITY: 'false'
        run: |
          pytest -q
