name: CI

on:
  push:
    branches: [ main, master, develop, feature/** ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        env:
          # Evita falhas por checagem de conectividade em ambientes sem Neo4j
          NEO4J_VERIFY_CONNECTIVITY: 'false'
        run: |
          pytest -q --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
